import { Database } from "./types";

// Dados de exemplo para o sistema já nascer demonstrável.
// PINs: Supervisor 1234 · Líder (João) 1111 · Auxiliar (Ana) 2222

export function criarSeed(): Database {
  const hoje = new Date();
  const diaISO = (offset: number) => {
    const d = new Date(hoje);
    d.setDate(d.getDate() + offset);
    return d.toISOString().slice(0, 10);
  };
  const isoAgora = hoje.toISOString();
  const periodo = isoAgora.slice(0, 7);

  return {
    usuarios: [
      { id: "u_sup", nome: "Pr. Marcos (Supervisor)", perfil: "supervisor", pin: "1234" },
      { id: "u_joao", nome: "João Silva", perfil: "lider", pin: "1111", grupoId: "g_tropical" },
      { id: "u_ana", nome: "Ana Souza", perfil: "auxiliar", pin: "2222", grupoId: "g_tropical" },
      { id: "u_paulo", nome: "Paulo Lima", perfil: "lider", pin: "3333", grupoId: "g_betel" },
    ],

    grupos: [
      {
        id: "g_tropical",
        nome: "GCA Jardim Tropical",
        liderId: "u_joao",
        liderNome: "João Silva",
        auxiliarNome: "Ana Souza",
        anfitriaoNome: "Maria Silva",
        endereco: "Rua das Palmeiras, 120 — Jardim Tropical",
        diaSemana: "Quinta-feira",
        horario: "19:30",
        supervisorNome: "Pr. Marcos",
        situacao: "saudavel",
        criadoEm: isoAgora,
      },
      {
        id: "g_betel",
        nome: "GCA Betel",
        liderId: "u_paulo",
        liderNome: "Paulo Lima",
        auxiliarNome: "",
        anfitriaoNome: "Paulo Lima",
        endereco: "Av. Central, 45 — Centro",
        diaSemana: "Terça-feira",
        horario: "20:00",
        supervisorNome: "Pr. Marcos",
        situacao: "sobrecarregado",
        criadoEm: isoAgora,
      },
    ],

    familias: [
      { id: "f_silva", nome: "Família Silva", criadoEm: isoAgora },
      { id: "f_oliveira", nome: "Família Oliveira", criadoEm: diaISO(-2) },
    ],

    pessoas: [
      {
        id: "p_joao",
        nomeCompleto: "João Silva",
        dataNascimento: "1985-03-12",
        telefone: "(11) 98888-1001",
        endereco: "Rua das Palmeiras, 120",
        bairro: "Jardim Tropical",
        estadoCivil: "casado",
        profissao: "Engenheiro",
        grupoId: "g_tropical",
        situacao: "membro",
        familiaId: "f_silva",
        parentesco: "esposo",
        criadoEm: isoAgora,
      },
      {
        id: "p_maria",
        nomeCompleto: "Maria Silva",
        dataNascimento: "1987-07-22",
        telefone: "(11) 98888-1002",
        endereco: "Rua das Palmeiras, 120",
        bairro: "Jardim Tropical",
        estadoCivil: "casado",
        profissao: "Professora",
        grupoId: "g_tropical",
        situacao: "membro",
        familiaId: "f_silva",
        parentesco: "esposa",
        criadoEm: isoAgora,
      },
      {
        id: "p_pedro",
        nomeCompleto: "Pedro Silva",
        dataNascimento: "2010-01-05",
        telefone: "",
        bairro: "Jardim Tropical",
        estadoCivil: "solteiro",
        grupoId: "g_tropical",
        situacao: "membro",
        familiaId: "f_silva",
        parentesco: "filho",
        criadoEm: isoAgora,
      },
      {
        id: "p_ana_filha",
        nomeCompleto: "Ana Silva",
        dataNascimento: "2013-09-18",
        bairro: "Jardim Tropical",
        estadoCivil: "solteiro",
        grupoId: "g_tropical",
        situacao: "novo_convertido",
        familiaId: "f_silva",
        parentesco: "filha",
        criadoEm: isoAgora,
      },
      {
        id: "p_carlos",
        nomeCompleto: "Carlos Mendes",
        dataNascimento: "1992-11-30",
        telefone: "(11) 97777-2003",
        bairro: "Jardim Tropical",
        estadoCivil: "solteiro",
        profissao: "Autônomo",
        grupoId: "g_tropical",
        situacao: "afastado",
        cuidadoUrgente: true,
        observacoes: "Passando por dificuldade financeira e desânimo.",
        criadoEm: isoAgora,
      },
      {
        id: "p_julia",
        nomeCompleto: "Júlia Oliveira",
        dataNascimento: "1995-04-10",
        telefone: "(11) 96666-3004",
        bairro: "Centro",
        estadoCivil: "solteiro",
        grupoId: "g_tropical",
        situacao: "visitante",
        familiaId: "f_oliveira",
        parentesco: "outro",
        criadoEm: diaISO(-2),
      },
      {
        id: "p_paulo",
        nomeCompleto: "Paulo Lima",
        dataNascimento: "1980-06-01",
        telefone: "(11) 95555-4005",
        bairro: "Centro",
        estadoCivil: "casado",
        profissao: "Comerciante",
        grupoId: "g_betel",
        situacao: "membro",
        criadoEm: isoAgora,
      },
    ],

    reunioes: [
      {
        id: "r_t3",
        grupoId: "g_tropical",
        data: diaISO(-21),
        tema: "O Bom Pastor — João 10",
        registros: [
          { pessoaId: "p_joao", presente: true },
          { pessoaId: "p_maria", presente: true },
          { pessoaId: "p_pedro", presente: true },
          { pessoaId: "p_ana_filha", presente: true },
          { pessoaId: "p_carlos", presente: false, motivoAusencia: "Trabalho", precisaLigacao: true },
          { pessoaId: "p_julia", presente: false },
        ],
        visitantes: [],
        criadoEm: diaISO(-21),
      },
      {
        id: "r_t2",
        grupoId: "g_tropical",
        data: diaISO(-14),
        tema: "Comunhão e cuidado mútuo",
        registros: [
          { pessoaId: "p_joao", presente: true },
          { pessoaId: "p_maria", presente: true },
          { pessoaId: "p_pedro", presente: true },
          { pessoaId: "p_ana_filha", presente: false, motivoAusencia: "Doente" },
          { pessoaId: "p_carlos", presente: false, motivoAusencia: "Não atendeu", precisaVisita: true },
          { pessoaId: "p_julia", presente: true },
        ],
        visitantes: [{ nome: "Roberto (vizinho)", telefone: "(11) 90000-0000" }],
        criadoEm: diaISO(-14),
      },
      {
        id: "r_t1",
        grupoId: "g_tropical",
        data: diaISO(-7),
        tema: "A oração que transforma",
        registros: [
          { pessoaId: "p_joao", presente: true },
          { pessoaId: "p_maria", presente: true },
          { pessoaId: "p_pedro", presente: false, motivoAusencia: "Viagem" },
          { pessoaId: "p_ana_filha", presente: true },
          { pessoaId: "p_carlos", presente: false, motivoAusencia: "Sem contato", precisaVisita: true, precisaLigacao: true },
          { pessoaId: "p_julia", presente: true },
        ],
        visitantes: [],
        criadoEm: diaISO(-7),
      },
    ],

    relatorios: [
      {
        id: "rel_carlos",
        pessoaId: "p_carlos",
        grupoId: "g_tropical",
        autorId: "u_joao",
        periodo,
        data: diaISO(-5),
        frequentandoGrupo: false,
        indoCultos: false,
        lendoBiblia: false,
        orando: false,
        precisaVisita: true,
        precisaAconselhamento: true,
        lutas: { financeira: true, emocional: true, espiritual: true },
        marcos: { afastamento: true },
        observacoesPastorais:
          "Carlos se afastou após perder o emprego. Demonstra desânimo. Precisa de visita pastoral com urgência e, se possível, apoio prático da igreja.",
        privacidade: "somente_supervisor",
        criadoEm: diaISO(-5),
      },
      {
        id: "rel_maria",
        pessoaId: "p_maria",
        grupoId: "g_tropical",
        autorId: "u_joao",
        periodo,
        data: diaISO(-5),
        frequentandoGrupo: true,
        indoCultos: true,
        lendoBiblia: true,
        orando: true,
        precisaVisita: false,
        precisaAconselhamento: false,
        lutas: {},
        marcos: {},
        observacoesPastorais: "Firme na fé, tem ajudado a acolher novos visitantes.",
        privacidade: "lider_e_supervisor",
        criadoEm: diaISO(-5),
      },
    ],
  };
}
